booking:
  property: Booking Profile Dev

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookingdb
    username: root
    password: 1000depan
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
