booking:
  property: Booking Profile Dev

spring:
  jpa:
    datasource:
      url: jdbc:mysql://localhost:3306/bookingdb
      username: root
      password: 1000depan
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
